#!/usr/bin/env python3
"""Render or verify standalone prompts from the protocol and missions."""

from __future__ import annotations

import argparse
import pathlib


HEADER = "<!-- Generated by scripts/render_prompts.py; edit the mission or protocol. -->\n\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=pathlib.Path, default=pathlib.Path("agents/prompts"))
    parser.add_argument("--check", action="store_true", help="fail when committed prompts are stale")
    args = parser.parse_args()

    root = pathlib.Path(__file__).resolve().parents[1]
    protocol = (root / "agents" / "PROTOCOL_AUTONOME.md").read_text(encoding="utf-8")
    missions = sorted((root / "agents" / "missions").glob("*.md"))
    output = args.output if args.output.is_absolute() else root / args.output
    expected = {
        mission_path.name: f"{HEADER}{mission_path.read_text(encoding='utf-8').rstrip()}\n\n{protocol.rstrip()}\n"
        for mission_path in missions
    }

    if args.check:
        stale = []
        for name, rendered in expected.items():
            path = output / name
            if not path.is_file() or path.read_text(encoding="utf-8") != rendered:
                stale.append(name)
        existing = {path.name for path in output.glob("*.md")} if output.exists() else set()
        stale.extend(sorted(existing - expected.keys()))
        if stale:
            print(f"stale prompts: {', '.join(sorted(set(stale)))}")
            return 1
        print(f"prompts ok: {len(expected)} file(s)")
        return 0

    output.mkdir(parents=True, exist_ok=True)
    for name, rendered in expected.items():
        (output / name).write_text(rendered, encoding="utf-8")
    for extra in output.glob("*.md"):
        if extra.name not in expected:
            extra.unlink()
    print(f"rendered {len(expected)} prompt(s) in {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
